from PIL import Image
import numpy as np
from textures import pixel_generator

a = np.full((8, 8), 128)
print(a)
im = Image.fromarray(a, mode="L")
print(im.getpixel((0, 0)))
print(im.getpixel((0, 1)))
print(im.getpixel((0, 2)))
print(im.getpixel((2, 0)))
print(im.getpixel((1, 1)))
print(im.getpixel((2, 2)))
print(im.getpixel((3, 3)))
print(im.getpixel((3, 3)))
#im.show()
a = np.full((8, 8, 3), 128)
print(a)
im = Image.fromarray(a, mode="RGB")
print(im.getpixel((0, 0)))
print(im.getpixel((1, 1)))
print(im.getpixel((2, 2)))
print(im.getpixel((3, 3)))
print(im.getpixel((3, 3)))
im.show()

im = Image.open("./input/beach.jpg", mode='r', formats=None)
im.show()
print(im.getpixel((0, 0)))
print(im.getpixel((1, 1)))
print(im.getpixel((2, 2)))
print(im.getpixel((3, 3)))
print(im.getpixel((3, 3)))
g = np.asarray(im)
print(g)
print(np.shape(g))

b = np.fromiter(pixel_generator(64), np.intc)
b = np.reshape(b, (64, 64))
im = Image.fromarray(b, mode='L')
im.show()
